# Generated by Django 6.0.4 on 2026-04-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desxription',
            new_name='description',
        ),
    ]
